sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t claudiokirchhoff/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true claudiokirchhoff/react-test npm test

after_success:
  - docker build -t claudiokirchhoff/multi-client ./client
  - docker build -t claudiokirchhoff/multi-nginx ./nginx
  - docker build -t claudiokirchhoff/multi-server ./server
  - docker build -t claudiokirchhoff/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push claudiokirchhoff/multi-client
  - docker push claudiokirchhoff/multi-nginx 
  - docker push claudiokirchhoff/multi-server
  - docker push claudiokirchhoff/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  environment: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-813479082211'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY